import type { CustomerOrder } from './types';

export const COUNTRIES = ['United States', 'Canada', 'Australia', 'Singapore', 'Hong Kong'];
export const PRODUCTS = [
  'Fiber Internet 300 Mbps',
  '5G Unlimited Mobile Plan',
  'Fiber Internet 1 Gbps',
  'Business Internet 500 Mbps',
  'VoIP Corporate Package',
];
export const CREATORS = [
  'Mr. Michael Harris',
  'Mr. Ryan Cooper',
  'Ms. Olivia Carter',
  'Mr. Lucas Martin',
];
export const PRODUCT_PRICES: { [key: string]: number } = {
  'Fiber Internet 300 Mbps': 49.99,
  '5G Unlimited Mobile Plan': 75.0,
  'Fiber Internet 1 Gbps': 89.99,
  'Business Internet 500 Mbps': 129.99,
  'VoIP Corporate Package': 250.0,
};

export const INITIAL_ORDERS: CustomerOrder[] = [
    {
      id: 'ord-001',
      firstName: 'John',
      lastName: 'Doe',
      email: 'john.doe@example.com',
      phone: '123-456-7890',
      address: '123 Main St',
      city: 'Anytown',
      state: 'CA',
      postalCode: '12345',
      country: 'United States',
      product: 'Fiber Internet 1 Gbps',
      quantity: 1,
      unitPrice: 89.99,
      totalAmount: 89.99,
      status: 'Completed',
      createdBy: 'Mr. Michael Harris',
      orderDate: new Date(new Date().setDate(new Date().getDate() - 10)).toISOString(),
    },
    {
      id: 'ord-002',
      firstName: 'Jane',
      lastName: 'Smith',
      email: 'jane.smith@example.com',
      phone: '987-654-3210',
      address: '456 Oak Ave',
      city: 'Someville',
      state: 'TX',
      postalCode: '67890',
      country: 'United States',
      product: '5G Unlimited Mobile Plan',
      quantity: 2,
      unitPrice: 75.0,
      totalAmount: 150.0,
      status: 'In Progress',
      createdBy: 'Ms. Olivia Carter',
      orderDate: new Date(new Date().setDate(new Date().getDate() - 5)).toISOString(),
    },
    {
      id: 'ord-003',
      firstName: 'Peter',
      lastName: 'Jones',
      email: 'peter.jones@example.com',
      phone: '555-123-4567',
      address: '789 Pine Ln',
      city: 'Metropolis',
      state: 'NY',
      postalCode: '10001',
      country: 'United States',
      product: 'Business Internet 500 Mbps',
      quantity: 1,
      unitPrice: 129.99,
      totalAmount: 129.99,
      status: 'Pending',
      createdBy: 'Mr. Ryan Cooper',
      orderDate: new Date().toISOString(),
    },
      {
      id: 'ord-004',
      firstName: 'Emily',
      lastName: 'Davis',
      email: 'emily.davis@example.ca',
      phone: '416-555-0123',
      address: '101 Maple Dr',
      city: 'Toronto',
      state: 'ON',
      postalCode: 'M5V 2E8',
      country: 'Canada',
      product: 'Fiber Internet 300 Mbps',
      quantity: 1,
      unitPrice: 49.99,
      totalAmount: 49.99,
      status: 'Completed',
      createdBy: 'Mr. Lucas Martin',
      orderDate: new Date(new Date().setDate(new Date().getDate() - 45)).toISOString(),
    },
    {
      id: 'ord-005',
      firstName: 'David',
      lastName: 'Wilson',
      email: 'david.wilson@example.com.au',
      phone: '02-9988-7766',
      address: '22 Acacia Ave',
      city: 'Sydney',
      state: 'NSW',
      postalCode: '2000',
      country: 'Australia',
      product: 'VoIP Corporate Package',
      quantity: 5,
      unitPrice: 250.00,
      totalAmount: 1250.00,
      status: 'Completed',
      createdBy: 'Mr. Michael Harris',
      orderDate: new Date(new Date().setDate(new Date().getDate() - 80)).toISOString(),
    },
];
